### ISSUE TITLE
Roboflow Integration Link in Docs 404's

### ISSUE THREAD

**Issue by yeldarby** [albumentations-team/albumentations.ai#105]
In the Albumentations Docs there are a few links to the Roboflow integration that are broken.

1. In the nav, the link to [/docs/roboflow](https://albumentations.ai/docs/roboflow) is broken
<img width="1481" alt="image" src="https://github.com/user-attachments/assets/90348ecf-f187-4f90-a710-12528e773fde">

2. In the [Integrations](https://albumentations.ai/docs/#integrations) section, the link to [/docs/integrations/roboflow/train-rt-detr-on-custom-dataset-with-transformers.md](https://albumentations.ai/docs/integrations/roboflow/train-rt-detr-on-custom-dataset-with-transformers.md) is broken.
<img width="546" alt="image" src="https://github.com/user-attachments/assets/3c0b18eb-53d6-4d01-9f97-03da4d4fe315">

**Comment by ternaus** [comment]
@yeldarby Thank you, fixed.
