### ISSUE TITLE
Diagram explaining keypoint scale is very misleading

### ISSUE THREAD

**Issue by Multihuntr** [albumentations-team/albumentations.ai#22]
The page describing keypoints augmentation implies that the scale is just the x component of the length, rather than actually being the hypotenuse length.

Page: https://albumentations.ai/docs/getting_started/keypoints_augmentation/

Diagram:
![diagram](https://github.com/albumentations-team/albumentations.ai/raw/master/mkdocs/src/docs/images/getting_started/augmenting_keypoints/keypoint_with_scale_and_angle.png)

**Comment by Multihuntr** [comment]
Here's my attempt at fixing it.

![keypoint-scale](https://user-images.githubusercontent.com/10515040/146309224-c3213029-f937-4930-8730-b1777150cb2d.png)

Here's the SVG:
[keypoint-scale.zip](https://github.com/albumentations-team/albumentations.ai/files/7724594/keypoint-scale.zip)

**Comment by creafz** [comment]
Hi. Thanks for the fixed image! I have added it to https://albumentations.ai/docs/getting_started/keypoints_augmentation/
