### ISSUE TITLE
Dimension Off by 1 for Bounding Box Documentation

### ISSUE THREAD

**Issue by FeynmanDNA** [albumentations-team/albumentations.ai#36]
Hi I am referring to this documentation page: https://github.com/albumentations-team/albumentations.ai/blob/master/mkdocs/src/docs/getting_started/bounding_boxes_augmentation.md

The example image is of dimension "The image width is 640 pixels, and its height is 480 pixels", so the image coordinates for the corners should be (0, 479) and not (0, 480). Similarly for (640, 480), it should be (639, 479).

Also Pascal Voc format is 1-indexed, so the conversion should convert the 0-indexed to 1-indexed for VOC xml compatible values.

**Comment by ternaus** [comment]
No, that's fine.

Box coordinated and pixel positions live in different spaces. =>

for image with shape (480, 640) box coordinates covering it should be (0, 0, 640, 480)
