### ISSUE TITLE
[docs] Searching for transform name does not find transform

### ISSUE THREAD

**Issue by MortenHannemose** [albumentations-team/albumentations.ai#6]
When searching for "HueSaturationValu" on https://albumentations.ai/docs/, the transform "HueSaturationValue" is hit number 9 in the returned search results.
However, if I search for the full name "HueSaturationValue", it does not find the transform.

Additionally, one would expect the transform to be returned as the first result for both search queries.

**Comment by creafz** [comment]
Hey, @MortenHannemose 

We use the default search plugin from [MkDocs](https://www.mkdocs.org/) and sometimes it returns unexpected or incomplete responses to search queries. I will try to evaluate alternatives such as tuning the default search plugin or using an external search engine such as Algolia.

**Comment by creafz** [comment]
As an experiment, I have changed the default site search to Algolia. It returns the `HueSaturationValue` transform as the first result for both queries, so I think it is a good start :) 

Please report if you encounter any issue with the new search engine.
