### ISSUE TITLE
[Enchancement] Add table with how transforms from Torchvision map to Albumentations

### ISSUE THREAD

**Issue by ternaus** [albumentations-team/albumentations.ai#66]

**Comment by ternaus** [comment]
Such old table exists in https://albumentations.ai/docs/examples/migrating_from_torchvision_to_albumentations/#albumentations-equivalents-for-torchvision-transforms

But we need:

1. A separate page
2. Update to the current state of transforms in both libraries
3. Add benchmarking results to show the advantage of moving to Albumentations

**Comment by Magdielian-code** [comment]
Please add a description 

I'd love to work on this.

**Comment by ternaus** [comment]
Added.

Could be found in https://albumentations.ai/docs/getting_started/augmentation_mapping/
