### ISSUE TITLE
Scroll left bar

### ISSUE THREAD

**Issue by Dipet** [albumentations-team/albumentations.ai#7]
Need add scroll support for area from navigation bar.
For example, when I open all examples I can not scroll and see all data
![Screenshot from 2020-10-28 16-29-40](https://user-images.githubusercontent.com/7512250/97442353-cfcc4380-193a-11eb-8d9f-b3b8ae88fb57.png)

**Comment by creafz** [comment]
Could you please share your OS and browser version? I checked the page using Mac OS 10.15.6 and Chrome 86, and the scroll seems to work. Here is a video - https://recordit.co/njBD2HqIII

**Comment by Dipet** [comment]
Scroll works, but It is works for whole page.
But better when we can scroll only left navigation bar, because whole page may be too large

**Comment by creafz** [comment]
Ah, I see. Do you want a scroll that behaves like the scroll on this page? https://docs.prefect.io/core/

**Comment by Dipet** [comment]
Yeah, if it will be looks like on example would be great.

**Comment by creafz** [comment]
This should be fixed now. Please reopen the issue if you encounter problems with the scroll.
